version: "3.3"

services:
  beedule:
    build:
      context: .
    container_name: beedule
    restart: unless-stopped
    ports:
      - "7601:3945"
    volumes:
      - /mnt/nas/data/beedule/custom.conf:/src/conf/custom.conf
      - /mnt/nas/data/beedule/beedule.sqlite:/src/database/beedule.sqlite
      - /mnt/nas/data/picsou/picsou.sqlite:/src/database/picsou.sqlite
      - /mnt/nas/data/picsou:/src/data/picsou

    networks:
      - db-network

networks:
  db-network:
    driver: bridge

# Pour reconstruire le container
# docker container ls -a | grep beedule
# docker container stop c1cdc677d547
# docker container rm c1cdc677d547

# docker ps -a | grep beedule | awk '{print $1}' | xargs docker rm -f
# docker-compose up -d --build

