version: "3.3"

services:
  beedule:
    build:
      context: .
    container_name: beedule
    restart: unless-stopped
    ports:
      - "7601:3945"
    volumes:
      - /mnt/nas/data/beedule/custom.conf:/src/conf/custom.conf
      - /mnt/nas/data/beedule/beedule.sqlite:/src/database/beedule.sqlite

# Pour reconstruire le container
# docker-compose up -d --build

