# https://gist.github.com/w0rldart/1d5c5204723690d6b5845e4d7da06595
# https://www.digitalocean.com/community/tutorials/how-to-use-traefik-1-7-21-as-a-reverse-proxy-for-docker-containers-on-centos-7-2"

version: "3.3"
services:
  portainer:
    image: portainer/portainer-ce
    container_name: portainer
    command: -H unix:///var/run/docker.sock
    ports:
      - "9080:9000"
    restart: always
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

  traefik:
    image: traefik:latest
    container_name: traefik
    restart: unless-stopped
    ports:
      - 9090:8080
      - 80:80
      - 443:443
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - certs:/letsencrypt
      - ./traefik.yaml:/etc/traefik/traefik.yaml
      - ./custom_services:/etc/traefik/custom_services
      - /mnt/nas/data/beedule:/log
    networks:
      - webgateway

  mysql:
    image: mariadb:latest
    container_name: mariadb
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: sme3-Aprt
      MYSQL_DATABASE: beedule
      MYSQL_USER: beedule
      MYSQL_PASSWORD: beedule
    volumes:
      - /mnt/nas/data/mariadb:/var/lib/mysql
    ports:
      - 3306:3306
    networks:
      - webgateway

  adminer:
    image: adminer
    container_name: adminer
    restart: unless-stopped
    ports:
      - 9070:8080
    networks:
      - webgateway

  beedule:
    build:
      context: .
    image: beedule:latest
    container_name: beedule
    restart: unless-stopped
    ports:
      - "7601:3945"
    volumes:
      - /mnt/nas/data/beedule/custom.conf:/src/beedule/conf/custom.conf
      - /mnt/nas/data/beedule/beedule.sqlite:/src/beedule/database/beedule.sqlite
      # - ./docker/secure-traefik.yaml:/src/beedule/docker/secure-traefik.yaml
      - /mnt/nas/data/picsou/picsou.sqlite:/src/beedule/database/picsou.sqlite
      - /mnt/nas/data/picsou:/src/beedule/data/picsou
      # - /home/billerot/Abri/foirexpo:/src/beedule/data/foirexpo
    networks:
      - webgateway

  web:
    image: nginx
    container_name: nginx
    restart: unless-stopped
    volumes:
    - ./site.conf:/etc/nginx/conf.d/site.conf    
    - ./nginx:/usr/share/nginx/html
    # - /home/billerot/Abri/foirexpo/public:/usr/share/nginx/html/foirexpo
    ports:
    - "7603:80"
    environment:
    - NGINX_HOST=pbillerot.freeboxos.fr
    - NGINX_PORT=80
    networks:
      - webgateway

  filebrowser:
    image: filebrowser/filebrowser:latest
    container_name: filebrowser
    restart: unless-stopped
    ports:
      - "7602:80"
    # command:
    #   - 'filebrowser config set --auth.method=proxy --auth.header=Remote-User'
      # - 'filebrowser'
      # - 'config'
      # - 'set'
      # - '--auth.method=proxy'
      # - '--auth.header=Remote-User'

    volumes:
      - /home/billerot/Abri/foirexpo/content:/srv
      - /mnt/nas/data/filebrowser/database.db:/database.db
      - ./filebrowser.json:/.filebrowser.json    

  navidrome:
    image: deluan/navidrome:latest
    container_name: navidrome
    user: 1000:1000 # should be owner of volumes
    ports:
      - "4533:4533"
    restart: unless-stopped
    environment:
      # Optional: put your config options customization here. Examples:
      ND_SCANINTERVAL: 1m
      ND_LOGLEVEL: info  
      ND_SESSIONTIMEOUT: 24h
      ND_BASEURL: "/nv"
    volumes:
      - "/mnt/sandisk/nas/data/navidrome:/data"
      - "/mnt/sandisk/nas/Musique:/music"

volumes:
  certs:

networks:
  webgateway:
    driver: bridge
    # driver_opts:
    #   com.docker.network.enable_ipv6: "true"
    # external:
    #     name: traefik

# Pour reconstruire le container
# docker container ls -a | grep beedule
# docker container stop c1cdc677d547
# docker container rm c1cdc677d547

# docker rmi nom de l'image


# docker ps -a | grep beedule | awk '{print $1}' | xargs docker rm -f
# docker-compose up -d --build restartr
# docker image prune -a

# Ouvrir une console
# docker container exec -it beedule /bin/bash
# docker container exec -it nginx /bin/bash
