api:
  dashboard: true
  insecure: true

providers:
  docker:
    exposedByDefault: false
    watch : true
    endpoint: "unix:///var/run/docker.sock"

  file:
    directory: /etc/traefik/custom_services/
    watch: true

entryPoints:
  web:
    address: :80
    http:
      redirections:
        entryPoint:
          to: websecure
          scheme: https

  websecure:
    address: :443
    http:
      tls:
        certResolver: letsencrypt
        options: intermediate
      middlewares:
      # - authelia-auth@file
      - ip-whitelist@file
      - secHeaders@file

accessLog:
  filePath: "/log/access.log"
  bufferingSize: 100

certificatesResolvers:
  letsencrypt:
    acme:
      email: "philippe.billerot@gmail.com"
      storage: "/letsencrypt/acme.json"
      httpChallenge:
        entryPoint: "web"

