
title: "Beedule"
info: "Framework de développement WEB en langage Go"
icon-file: "/bee/static/img/beedule.png"
# Paramètres globaux
parameters:
  __amount_min: 1200 # mise minimum
  __cost: 0.0047 # coût en % d'une transaction
  __optimum: 0.03 # seuil en % minimum pour vente

# Liste des applications gérées
applications:
  admin:
    name: "admin"
    title: "Gestion du site"
    image: "/bee/static/img/tools.png"
    group: admin
    tables-views:
    - table-name: users
      view-name: vall
    - table-name: groups
      view-name: vall
  # picsou:
  #   title: "Picsou, pour bricoler sur la bourse"
  #   group: picsou
  #   image: "/bee/static/img/picsou.jpg"
  #   views: 
  #   - table-name: orders
  #     view-name: vachat
  #   - table-name: orders
  #     view-name: vvente
  #   - table-name: orders
  #     view-name: vgraph
  #   - table-name: ptf
  #     view-name: vall
  #   - table-name: ptf
  #     view-name: vdiapo
  #   - table-name: ptf
  #     view-name: vtop
  #   - table-name: ptf
  #     view-name: vntop
  #   - table-name: quotes
  #     view-name: vlast

