setting:
  alias-db: picsou
  key: ptf_id
  col-display: ptf_name
  icon-name: "building"

views:
  vall:
    form-edit: "fedit"
    form-view: "fview"
    group: "picsou"
    deletable: true
    title: "Les Valeurs"
    icon-name: "city"
    mask:
      header:
        - ptf_name
        - ptf_id
      meta:
        - ptf_enabled
        - ptf_top
      description:
        - ptf_rem
      extra:
        - ptf_quote
        - ptf_gain
    elements:
      ptf_id:
      ptf_name:
      ptf_enabled:
      ptf_top:
      ptf_rem:
      ptf_quote:
      ptf_gain:
    # where: "ptf_enabled = '1' and ptf_top = '1'"
    order-by: "ptf_name"
    actions:
      - label: "Effacer les remarques..."
        sql:
          - "update ptf set ptf_rem = ''"
        with-confirm: true
  vdiapo:
    title: "Graphiques"
    form-edit: "fedit"
    form-view: "fview"
    group: "picsou"
    icon-name: "photo video"
    type: "image"
    class-sql: "select case when '{ptf_note}' like '%achat%' then 'crud-gondole' else '' end"
    elements:
      ptf_id:
        order: 10
      ptf_name:
        order: 20
      ptf_top:
        order: 25
      ptf_rem:
        order: 30
      ptf_note:
        order: 40
      ptf_gain:
        order: 50
      ptf_quote:
        order: 60
      _image_analyse:
        order: 120
      # _chart_quotes:
      #   order: 130
    order-by: "ptf_name"
    where: "ptf_enabled = '1'"
    actions:
      - label: "Effacer les remarques..."
        sql:
          - "update ptf set ptf_rem = ''"
        with-confirm: true

  vtop:
    title: "Graphiques TOP"
    form-edit: "fedit"
    form-view: "fview"
    group: "picsou"
    icon-name: "photo video"
    type: "image"
    class-sql: "select case when '{ptf_note}' like '%achat%' then 'crud-gondole' else '' end"
    elements:
      ptf_id:
        order: 10
      ptf_name:
        order: 20
      ptf_top:
        order: 25
      ptf_rem:
        order: 30
      ptf_note:
        order: 40
      ptf_gain:
        order: 50
      ptf_quote:
        order: 60
      _image_analyse:
        order: 120
      # _chart_quotes:
      #   order: 130

    order-by: "ptf_name"
    where: "ptf_enabled = '1' and ptf_top = '1'"
    actions:
      - label: "Effacer les remarques..."
        sql:
          - "update ptf set ptf_rem = ''"
        with-confirm: true

  vntop:
    title: "Graphiques NON TOP"
    form-edit: "fedit"
    form-view: "fview"
    group: "picsou"
    icon-name: "photo video"
    type: "image"
    class-sql: "select case when '{ptf_note}' like '%achat%' then 'crud-gondole' else '' end"
    elements:
      ptf_id: 
        order: 10
      ptf_name: 
        order: 20
      ptf_top: 
        order: 25
      ptf_rem: 
        order: 30
      ptf_note: 
        order: 40
      ptf_gain: 
        order: 50
      ptf_quote: 
        order: 60
      _image_analyse:
        order: 120
      # "_chart_quotes: 
      #   order: 130
    order-by: "ptf_name"
    where: "ptf_enabled = '1' and ptf_top <> '1'"
    actions:
      - label: "Effacer les remarques..."
        sql: 
          - "update ptf set ptf_rem = ''"
        with-confirm: true

forms:
  fview:
    title: "Fiche Valeur"
    group: "picsou"
    elements: 
      ptf_id: 
        order: 10
      ptf_name: 
        order: 20
      ptf_enabled: 
        order: 30
      ptf_top: 
        order: 50
      ptf_note: 
        order: 55
      ptf_rem: 
        order: 60
      ptf_quote: 
        order: 70
      ptf_gain: 
        order: 80
      _action_buy: 
        order: 90
      _chart_quotes: 
        order: 110
      _image_analyse:
        order: 120

  fadd:
    title: "Ajout d'une valeur"
    group: "picsou"
    elements: 
      ptf_id: 
        order: 10
      ptf_name:
        order: 20
      ptf_isin:
        order: 30

  fedit:
    title: "Fiche Valeur"
    group: "picsou"
    elements: 
      ptf_id: 
        order: 10
      ptf_name: 
        order: 20
      ptf_isin: 
        order: 30
      ptf_enabled:
        order: 40
      ptf_top: 
        order: 50
      ptf_note: 
        order: 60
        protected: true
      ptf_rem: 
        order: 70
    post-sql: 
      - "UPDATE PTF set ptf_note = 'TOP' where ptf_note = '' and ptf_top = '1' and ptf_id = '{ptf_id}'"
      - "UPDATE PTF set ptf_note = '' where ptf_note = 'TOP' and ptf_top = '0' and ptf_id = '{ptf_id}'"

elements: 
  _action_buy:
    type: action
    label-long: "Acheter la valeur..."
    group: "trader"
    actions: 
      - label: "Acheter cette valeur"
        url: "/bee/add/picsou/orders/vachat/feditbuy?orders_order=buy&orders_ptf_id={ptf_id}&orders_quote={ptf_quote}&orders_buy={ptf_quote}"
  ptf_id:
    type: text
    label-long: "Valeur"
    label-short: "Valeur"
  ptf_name:
    type: text
    label-long: "Nom"
    label-short: "Nom"
  ptf_isin:
    type: text
    label-long: "Code ISIN"
    label-short: "ISIN"
  ptf_note:
    type: text
    label-long: "Note "
    label-short: "Note"
  ptf_rem:
    type: text
    label-long: "Remarque"
    label-short: "Remarque"
    class-sql: "select 'orange'"
  ptf_enabled:
    type: checkbox
    label-long: "Valeur Active"
    label-short: "Active"
  ptf_top:
    type: checkbox
    label-long: "TOP"
    label-short: "TOP"
  ptf_quote:
    type: amount
    label-long: "Quote du jour"
    label-short: "Quote"
  ptf_gain:
    type: percent
    label-long: "Gain du jour"
    label-short: "Gain"
    class-sql: "select case when {ptf_gain} > 0 then 'green' when {ptf_gain} < 0 then 'red' end"
  _image_day:
    type: "image"
    label-long: "Graph du jour"
    label-short: "Graph J"
    params: 
      path: "/bee/data/picsou/png/day/{ptf_id}.png"
      url: "/bee/data/picsou/png/day/{ptf_id}.png"
      header: 
        - ptf_name
        - ptf_id
      description: 
        - ptf_rem
      extra: 
        - ptf_top
        - ptf_quote
        - ptf_gain
  _image_histo:
    type: "image"
    label-long: "Historique sur 1 mois"
    label-short: "Histo"
    params: 
      path: "/bee/data/picsou/png/quotes/{ptf_id}.png"
      url: "/bee/data/picsou/png/quotes/{ptf_id}.png"
      header: 
        - ptf_name
        - ptf_id
      extra: 
        - ptf_top
        - ptf_quote
        - ptf_gain
  _image_analyse:
    type: "image"
    label-long: "Analyse sur 7 mois"
    label-short: "Analyse"
    params: 
      path: "/bee/data/picsou/png/ana/{ptf_id}.gif"
      url: "/bee/data/picsou/png/ana/{ptf_id}.gif"
      header: 
        - ptf_name
        - ptf_id"
      extra: 
        - ptf_top
        - ptf_quote
        - ptf_gain
  _chart_quotes:
    type: "image"
    label-long: "Cotation sur 1 mois"
    label-short: "Cotation"
    dataset: 
      classjquery: "select 'bee-chart-quotes'"
      title: "select 'Cours deptf_id}'"
      quotes: "select open as matin, close as soir from quotes where id = '{ptf_id}' order by date"
      quotep: "select (open-close1)*100/close1 as matin, (close-close1)*100/close1 as soir from quotes where id = '{ptf_id}' order by date"
      labels: "select printf('%s-%s',substr(date,9,2),substr(date,6,2)) as 'matin', '-' as 'soir' from quotes where id = '{ptf_id}' order by date"
      minp: "select (low-close1)*100/close1 as matin, (low-close1)*100/close1 as soir from quotes where id = '{ptf_id}' order by date"
      maxp: "select (high-close1)*100/close1 as matin, (high-close1)*100/close1 as soir from quotes where id = '{ptf_id}' order by date"
      min: "select min(low) as min from quotes where id = '{ptf_id}'"
      max: "select max(high) as max from quotes where id = '{ptf_id}'"
      seuilv: "select orders_cost_price + orders_cost_price *__optimum} from orders where orders_ptf_id = '{ptf_id}' and orders_order = 'buy'"
      seuilr: "select orders_cost_price from orders where orders_ptf_id = '{ptf_id}' and orders_order = 'buy'"
