# Table des Clients
setting:
  alias-db: chinook
  key: EmployeeId
  col-display: FirstName
  icon-name: "user tie"

elements:
  EmployeeId:
    type: number
    label-long: "Id"
    label-short: "Id"
  FirstName:
    type: text
    label-long: "Nom"
    label-short: "Nom"
  LastName:
    type: text
    label-long: "Prénom"
    label-short: "Prénom"
  Title:
    type: text
    label-long: "Titre"
    label-short: "Titre"
  ReportsTo:
    type: number
    label-long: "Chargé(e) de"
    label-short: "Chargé(e)"
  BirthDate:
    type: date
    label-long: "Date de naissance"
    label-short: "Né(e)"
  HireDate:
    type: date
    label-long: "Date embauche"
    label-short: "Embauché(e) le"
  Address:
    type: textarea
    label-long: "Adresse"
    label-short: "Adresse"
  City:
    type: text
    label-long: "Ville"
    label-short: "Ville"
  State:
    type: text
    label-long: "État"
    label-short: "État"
  Country:
    type: text
    label-long: "Région"
    label-short: "Région"
  PostalCode:
    type: text
    label-long: "Code postal"
    label-short: "Code postal"
  Phone:
    type: text
    label-long: "Téléphone"
    label-short: "Téléphone"
  Fax:
    type: text
    label-long: "Fax"
    label-short: "Fax"
  Email:
    type: email
    label-long: "Email"
    label-short: "Email"

views:
  vall:
    form-add: fedit
    form-edit: fedit
    deletable: false
    type: table
    group: chinook
    title: "Employés"
    icon-name: "user tie"
    order-by: EmployeeId
    mask:
      header:
        - EmployeeId
      meta:
      description:
        - FirstName
      extra:
    elements:
      EmployeeId:
        order: 10
      FirstName:
        order: 20
      LastName:
        order: 30
      Title:
        order: 40
      ReportsTo:
        order: 50
      BirthDate:
        order: 60
      HireDate:
        order: 70
      Address:
        order: 80
      City:
        order: 90
      State:
        order: 100
      Country:
        order: 110
      PostalCode:
        order: 120
      Phone:
        order: 130
      Fax:
        order: 140
      Email:
        order: 150

forms:
  fedit:
    title: "Client"
    groupe: chinook
    elements:
      EmployeeId:
        order: 10
      FirstName:
        order: 20
      LastName:
        order: 30
      Title:
        order: 40
      ReportsTo:
        order: 50
      BirthDate:
        order: 60
      HireDate:
        order: 70
      Address:
        order: 80
      City:
        order: 90
      State:
        order: 100
      Country:
        order: 110
      PostalCode:
        order: 120
      Phone:
        order: 130
      Fax:
        order: 140
      Email:
        order: 150
