# Table des PlayLists
setting:
  alias-db: chinook
  key: PlaylistId
  col-display: Name
  icon-name: "align justify"

elements:
  PlaylistId:
    type: numeric
    label-long: "Id"
    label-short: "Id"
  Name:
    type: text
    label-long: "Playliste"
    label-short: "Playliste"

views:
  vall:
    form-add: fedit
    form-edit: fedit
    deletable: false
    type: table
    group: chinook
    title: "Playliste"
    icon-name: "align justify"
    order-by: Name
    mask:
      header:
        - PlaylistId
      meta:
      description:
        - Name
      extra:
    elements:
      PlaylistId:
        order: 10
      Name:
        order: 20

forms:
  fedit:
    title: "PlayListe de musique"
    groupe: chinook
    elements:
      PlaylistId:
        order: 10
      Name:
        order: 20
