http:
  routers:
    filebrowser:
      entryPoints: 
      - websecure
      rule: "Host(`pbillerot.freeboxos.fr`) && PathPrefix(`/fb`)"
      service: filebrowser

  services:
    filebrowser:
      loadBalancer:
        servers:
        - url: "http://192.168.1.76:7602/"
