http:
  routers:
    foirexpo:
      entryPoints: 
      - websecure
      rule: "Host(`pbillerot.freeboxos.fr`) && PathPrefix(`/foirexpo`)"
      service: foirexpo

  services:
    foirexpo:
      loadBalancer:
        servers:
        - url: "https://maixentexpo.github.io/foirexpo"
