http:
  middlewares:
    secHeaders:
      headers:
        accessControlAllowOrigin: "origin-list-or-null"
        accessControlMaxAge: 100
        addVaryHeader: true
        browserXssFilter: true
        contentTypeNosniff: true
        frameDeny: true

        stsIncludeSubdomains: true
        stsPreload: true
        stsSeconds: 315360000
        forceSTSHeader: true

        sslRedirect: true
        sslForceHost: true
        sslHost: 'pbillerot.freeboxos.fr'

        customFrameOptionsValue: "SAMEORIGIN"
        # contentSecurityPolicy: "script-src 'self'; img-src 'self'"
        referrerPolicy: "same-origin"
        featurePolicy: "vibrate 'self'; geolocation 'self'; midi 'self'; notifications 'self'; push 'self'; microphone 'none'; camera 'none'; magnetometer 'none'; gyroscope 'none'; speaker 'none'; vibrate 'self'; fullscreen 'self'"

    ip-whitelist:
      ipWhiteList:
        sourceRange:
          - "127.0.0.1"
          - "192.168.1.254"
        # ipStrategy:
        #   depth: 2          
        # ipStrategy:
        #   excludedIPs:
        #     - "110.153.64.45"
        #     - "113.247.4.215"

    bee-auth:
    # The following request properties are provided to the forward-auth target endpoint as `X-Forwarded-` headers.

    # | Property          | Forward-Request Header |
    # |-------------------|------------------------|
    # | HTTP Method       | X-Forwarded-Method     |
    # | Protocol          | X-Forwarded-Proto      |
    # | Host              | X-Forwarded-Host       |
    # | Request URI       | X-Forwarded-Uri        |
    # | Source IP-Address | X-Forwarded-For        |
      forwardAuth:
        # address: "http://192.168.1.76:3945/auth" # ok pour cette url
        address: "http://192.168.1.76:7601/auth" # ok pour cette url
        # address: "http://pbillerot.freeboxos.fr/auth"
        trustForwardHeader: true
        authResponseHeaders:
        - "Remote-User"
        - "Remote-Groups"
        - "Remote-Name"
        - "Remote-Email"
