http:
  routers:
    navidrome:
      entryPoints: 
      - websecure
      rule: "Host(`pbillerot.freeboxos.fr`) && PathPrefix(`/nv`)"
      service: navidrome
      middlewares:
      - secHeaders@file

  services:
    navidrome:
      loadBalancer:
        servers:
        - url: "http://172.17.0.1:4533/"
