CREATE TABLE "rubriques" (
	"rub_amount"	REAL,
	"rub_checkbox"	INTEGER,
	"rub_counter"	INTEGER,
	"rub_date"	TEXT,
	"rub_email"	TEXT,
	"rub_float"	REAL,
	"rub_image"	BLOB,
	"rub_list"	TEXT,
	"rub_number"	INTEGER,
	"rub_pdf"	TEXT,
	"rub_percent"	REAL,
	"rub_tag"	TEXT,
	"rub_text"	TEXT,
	"rub_textarea"	TEXT,
	"rub_time"	TEXT,
	"rub_radio"	TEXT,
	"rub_url"	TEXT,
	PRIMARY KEY("rub_counter" AUTOINCREMENT)
)